### ISSUE TITLE
[BUG] Can't connect because of a whitelist error: 403 Forbidden

### ISSUE THREAD

**Issue by saleemdev** [nikkothari22/frappe-js-sdk#9]
**Describe the bug**
The `auth.LiginWithUsernamePassword` request returns a forbidden 403 error described below.

```
{exc_type: "PermissionError", exception: "frappe.exceptions.PermissionError: Not permitted",…}
exc: "[\"Traceback (most recent call last):\\n  File \\\"apps/frappe/frappe/app.py\\\", line 69, in application\\n    response = frappe.api.handle()\\n  File \\\"apps/frappe/frappe/api.py\\\", line 55, in handle\\n    return frappe.handler.handle()\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 37, in handle\\n    data = execute_cmd(cmd)\\n  File \\\"apps/frappe/frappe/handler.py\\\", line 72, in execute_cmd\\n    is_whitelisted(method)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 749, in is_whitelisted\\n    throw(_(\\\"Not permitted\\\"), PermissionError)\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 503, in throw\\n    msgprint(\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 478, in msgprint\\n    _raise_exception()\\n  File \\\"apps/frappe/frappe/__init__.py\\\", line 433, in _raise_exception\\n    raise raise_exception(msg)\\nfrappe.exceptions.PermissionError: Not permitted\\n\"]"
exc_type: "PermissionError"
exception: "frappe.exceptions.PermissionError: Not permitted"
_server_messages: "[\"{\\\"message\\\": \\\"Not permitted\\\", \\\"title\\\": \\\"Message\\\", \\\"indicator\\\": \\\"red\\\", \\\"raise_exception\\\": 1}\"]"
```

**To Reproduce**
![image](https://user-images.githubusercontent.com/12731579/180129613-bd90e159-542e-4f5a-a757-18bf7bf6ca3d.png)

**Expected behavior**
A connection 200 OK

Sorry I am just asking for help incase I made a mistake.

**Comment by nikkothari22** [comment]
Hi @saleemdev ,

What version of Frappe and ERPNext are you using right now?

The library makes a call to the login method available in Frappe as mentioned [here](https://frappeframework.com/docs/v13/user/en/api/rest#2-password-based-authentication).

I see your Frappe app is hosted on http://ploti.zahasystems.online. Is your client app hosted on a separate domain?

**Comment by nikkothari22** [comment]
Hey @saleemdev - were you able to fix the problem?

**Comment by saleemdev** [comment]
Hi, I did not proceed with this task but I will raise the issue again on another thread later, once I get started. It might just work ;) Sorry for the delayed response.
